export const
    UNIVERSAL_BAR_WIDTH = 2,
    UNIVERSAL_BAR_GAP = 2,
    UNIVERSAL_BAR_RADIUS = 20,
    UNIVERSAL_AUTO_PLAY = false,
    UNIVERSAL_CURSOR_WIDTH = 2,
    UNIVERSAL_WAVEFORM_HEIGHT = 100,
    UNIVERSAL_ENVELOPE_INITIAL_VOLUME = .75,
    UNIVERSAL_ENVELOPE_DRAG_POINT_SIZE = 8,
    UNIVERSAL_ENVELOPE_FADE_IN_END = 5,
    UNIVERSAL_ENVELOPE_LINE_WIDTH = 1,
    UNIVERSAL_ENVELOPE_LINE_COLOR = `rgba(252, 96, 97, .6)`;
